name: tawakkalna_sdk_flutter
description: Flutter SDK for Tawakkalna - Saudi Arabia's super app. Access government services, user data, and documents seamlessly in alignment with Vision 2030.
version: 0.0.5-alpha.5
repository: https://github.com/hossameldinmi/tawakkalna_sdk_flutter

platforms:
  web:

topics:
  - tawakkalna
  - sdk
  - saudi-arabia
  - government-services
  - ksa

screenshots:
  - description: The package logo.
    path: doc/icon.png 
  - description: (iOS)(Mock-Data) Example app showcasing getting user data.
    path: doc/screenshot-1.png
  - description: (Web)(Mock-Data) Example app showcasing getting user data.
    path: doc/screenshot-2.png
  - description: (Web)(Mock-Data) Example app showing logs.
    path: doc/screenshot-3.png
    
environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling yto maintain consistency when
  # adding or updating assets for this project.

    # -------------------
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/tawakkalna_sdk_flutter/assets/web/twkhelper.js
    - packages/tawakkalna_sdk_flutter/assets/web/twkhelper_mock.js
    - assets/mock_profile1.0.2.json
